export const metadata = {
  title: "AKDAGIZUS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="bg-gradient-to-b from-[#55b3] to-[#55B3E6] min-h-screen">
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content={metadata.description} />
      <title>{metadata.title}</title>
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=optional"
        rel="stylesheet"
      />
      <link href="../public/assets/Fonts/Poppins" rel="stylesheet" />
      <link rel="icon" href="/favicon.ico" />
      <nav className="sticky top-0 left-0 z-50 w-full h-16 flex items-center justify-around mt-0 text-white bg-gradient-to-b from-[#55b3] to-[#55B3E6]">
        <img
          src="https://i.ibb.co/rQ5cTLX/NWDC.png"
          alt="logo Night Login Web Community"
          srcset=""
          className="w-12 h-12"
        />
        <div className="text-base w-1/3">
          <p className="pt-0 w-28 text-center">AKDAGIZUS</p>
        </div>
      </nav>
      {children}
    </div>
  );
}
